export type Category = 'Basics' | 'Charts' | 'Company Health' | 'Risk' | 'Strategies'
export const CATEGORIES: readonly ['All', ...Category[]] = ['All', 'Basics', 'Charts', 'Company Health', 'Risk', 'Strategies']

export interface Term {
  term: string
  category: Category
  simple: string
  explanation: string
  example?: string
  tip?: string
}

export function termToSlug(term: string): string {
  return term
    .toLowerCase()
    .replace(/[\/\(\)]/g, '')
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
}

export const TERMS: Term[] = [
  // ─── Basics ────────────────────────────────────────────────────────────────
  { term: 'Stock', category: 'Basics', simple: 'A tiny piece of ownership in a company', explanation: 'When you buy a stock, you own a small slice of that company. If the company does well, your slice is worth more.', example: 'Buy 1 share of Apple = own a tiny piece of Apple Inc.', tip: 'Think of it like buying a slice of a pizza — you own that slice.' },
  { term: 'Share', category: 'Basics', simple: 'One unit of a stock', explanation: 'A share is just one single piece of a company\'s stock. Companies split their ownership into millions of shares so regular people can afford to buy in.', example: 'Apple has about 15 billion shares. You might own 5 of them.' },
  { term: 'Ticker Symbol', category: 'Basics', simple: 'The short code used to identify a stock', explanation: 'Every publicly traded company has a unique abbreviation called a ticker symbol. It\'s how the market identifies that company. You type it into any trading app to find the stock.', example: 'Apple = AAPL, Tesla = TSLA, Google = GOOGL, Microsoft = MSFT.', tip: 'Ticker symbols are always a few letters long — usually 1 to 5 characters.' },
  { term: 'Market Cap', category: 'Basics', simple: 'Total value of a company', explanation: 'Multiply the stock price by the number of shares. That\'s how much the entire company is worth according to the market.', example: 'Stock at $100 × 1 billion shares = $100B market cap', tip: 'Common convention: under ~$2B = small-cap, $2B–$10B = mid-cap, over $10B = large-cap. Definitions vary — Russell and S&P use different thresholds that shift with each index rebalance.' },
  { term: 'Portfolio', category: 'Basics', simple: 'All your investments together', explanation: 'Your portfolio is the collection of all the stocks, ETFs, and other investments you own. Think of it as your investment "bag."', example: 'You own AAPL, TSLA, and NVDA — those 3 together are your portfolio.' },
  { term: 'Dividend', category: 'Basics', simple: 'Cash a company pays you just for owning their stock', explanation: 'Some companies share their profits with shareholders by paying dividends — usually every 3 months. You don\'t have to do anything to receive them.', example: 'Own 100 shares of Coca-Cola paying $0.46/share = $46 every quarter.', tip: 'Not all stocks pay dividends. Growth companies usually don\'t.' },
  { term: 'ETF', category: 'Basics', simple: 'A basket of many stocks in one', explanation: 'Instead of buying 500 individual stocks, you buy one ETF that contains all 500. It spreads your risk automatically.', example: 'SPY ETF = owns all 500 companies in the S&P 500.', tip: 'Great for beginners — instant diversification.' },
  { term: 'Index', category: 'Basics', simple: 'A scoreboard for a group of stocks', explanation: 'An index tracks the performance of a specific group of companies. The S&P 500 tracks America\'s 500 biggest companies.', example: 'S&P 500, Dow Jones, and Nasdaq are the three biggest indexes.' },
  { term: 'Bull Market', category: 'Basics', simple: 'When stocks are going up', explanation: 'A bull market is when stock prices are rising and investors are optimistic. Generally means prices are up 20%+ from recent lows.', tip: 'Bulls charge upward — so does the market in a bull market.' },
  { term: 'Bear Market', category: 'Basics', simple: 'When stocks are falling', explanation: 'A bear market means prices have dropped 20% or more from recent highs. Usually tied to recessions or bad economic news.', tip: 'Bears swipe downward — just like a bear market.' },
  { term: 'IPO', category: 'Basics', simple: 'When a company goes public for the first time', explanation: 'An Initial Public Offering is when a private company sells shares to regular people for the first time. It\'s the company\'s debut on the stock market.', example: 'Reddit went public in 2024 — that was their IPO.' },
  { term: 'Broker', category: 'Basics', simple: 'The app or platform where you buy stocks', explanation: 'A broker is the middleman between you and the stock market. Apps like Robinhood, Fidelity, and Schwab are all brokers.', tip: 'Always use a regulated, reputable broker — never random websites.' },
  { term: 'Liquidity', category: 'Basics', simple: 'How easy it is to buy or sell something quickly', explanation: 'A liquid stock has lots of buyers and sellers so you can exit fast. An illiquid stock might take days to sell.', example: 'Apple is very liquid. A tiny penny stock might not be.' },
  { term: 'Sector', category: 'Basics', simple: 'A group of companies in the same type of business', explanation: 'The stock market is divided into sectors — Technology, Healthcare, Finance, Energy, and more. Companies in the same sector tend to move together when news hits their industry.', example: 'Apple, Microsoft, and Nvidia are all in the Technology sector.', tip: 'Diversifying across sectors reduces your risk — don\'t put everything in one industry.' },
  { term: 'Stock Split', category: 'Basics', simple: 'When a company divides its shares into more, cheaper pieces', explanation: 'If a stock is at $1000 and the company does a 10-for-1 split, you get 10 shares worth $100 each. You still own the same total value — it\'s like breaking a $100 bill into ten $10 bills.', example: 'Apple did a 4-for-1 stock split in 2020 to make shares more affordable.', tip: 'Splits don\'t change the company\'s value — just the number of shares.' },
  { term: 'Buyback', category: 'Basics', simple: 'When a company buys back its own shares', explanation: 'Instead of paying dividends, companies sometimes use their profits to repurchase their own shares from the market. This reduces the number of shares, which means each remaining share represents a bigger piece of the company.', tip: 'Buybacks usually push the stock price up. A sign the company thinks its own stock is cheap.' },
  { term: 'Yield', category: 'Basics', simple: 'The income you earn on an investment as a percentage', explanation: 'Yield tells you how much return you\'re getting from a stock\'s dividends or a bond\'s interest, expressed as a percentage of the price you paid.', example: 'Stock costs $100, pays $4/year in dividends = 4% yield.', tip: 'High yields can look attractive but sometimes signal trouble — the price fell sharply.' },
  { term: 'Pre-Market Trading', category: 'Basics', simple: 'Trading that happens before the market officially opens', explanation: 'The stock market officially opens at 9:30 AM ET, but you can trade from 4 AM ET in pre-market. Volume is low and prices can be volatile. Earnings reports often drop before market open, causing big pre-market moves.', tip: 'Pre-market prices can swing wildly. Don\'t panic based on pre-market alone.' },
  { term: 'After-Hours Trading', category: 'Basics', simple: 'Trading after the market closes at 4 PM ET', explanation: 'After the market closes at 4 PM ET, you can still trade until 8 PM ET. Like pre-market, volume is low and spreads are wider. Earnings released after close cause the biggest after-hours moves.', tip: 'The after-hours price often stabilizes once regular trading opens the next day.' },

  // ─── Charts ────────────────────────────────────────────────────────────────
  { term: 'Candlestick', category: 'Charts', simple: 'A chart shape that shows a stock\'s price movement in a time period', explanation: 'Each candlestick shows the opening price, closing price, highest price, and lowest price for a specific time period. Green = price went up. Red = price went down.', tip: 'The "wick" (thin line) shows the highest and lowest price. The "body" shows open and close.' },
  { term: 'Support Level', category: 'Charts', simple: 'A price where a stock tends to stop falling', explanation: 'Support is a price level where buyers historically step in and stop the stock from dropping further. Like a floor.', example: 'If AAPL keeps bouncing at $150, that\'s a support level.', tip: 'If a stock breaks below support, it often falls a lot further.' },
  { term: 'Resistance Level', category: 'Charts', simple: 'A price where a stock tends to stop rising', explanation: 'Resistance is a price level where sellers historically push the stock back down. Like a ceiling.', example: 'If TSLA keeps failing to break $300, that\'s resistance.', tip: 'If a stock breaks above resistance, it often shoots up fast.' },
  { term: 'Moving Average', category: 'Charts', simple: 'The average price of a stock over a set number of days', explanation: 'A 50-day moving average is the average closing price over the last 50 days. It smooths out daily noise and shows the trend.', tip: 'Stock above its 200-day moving average = generally healthy trend.' },
  { term: 'Volume', category: 'Charts', simple: 'How many shares were traded today', explanation: 'Volume tells you how active a stock is. High volume means lots of buyers and sellers. A big price move on high volume = more credible.', tip: 'Always check volume when a stock spikes. Low volume spike = suspicious.' },
  { term: 'Breakout', category: 'Charts', simple: 'When a stock bursts above a resistance level', explanation: 'A breakout happens when a stock pushes through a price it\'s been stuck below. Often leads to a big move upward.', example: 'Stock stuck at $50 for months suddenly surges to $55 on high volume = breakout.' },
  { term: '52-Week High', category: 'Charts', simple: 'The highest price a stock has been in the last year', explanation: 'The 52-week high shows the peak price over the past 52 weeks. Stocks near their 52-week high are often in strong uptrends.', tip: 'Breaking above a 52-week high is often a very bullish signal.' },
  { term: 'RSI', category: 'Charts', simple: 'A score (0–100) showing if a stock is overbought or oversold', explanation: 'RSI (Relative Strength Index) measures how fast a stock is moving. Above 70 = might be overbought (due for a pullback). Below 30 = might be oversold (due for a bounce).', tip: 'RSI is just one tool — never use it alone.' },
  { term: 'MACD', category: 'Charts', simple: 'A momentum indicator showing when a trend might be changing', explanation: 'MACD (Moving Average Convergence Divergence) compares two moving averages to show whether momentum is building or fading. When the MACD line crosses above the signal line, it\'s a bullish sign. When it crosses below, bearish.', tip: 'Best used with other indicators — not reliable on its own.' },
  { term: 'Bollinger Bands', category: 'Charts', simple: 'Lines around a stock\'s price showing its normal range', explanation: 'Bollinger Bands are three lines: a moving average in the middle, and two bands above and below based on volatility. When a stock touches the upper band, it may be overbought. Lower band = potentially oversold.', tip: 'When the bands squeeze tight, a big move is often coming soon.' },
  { term: 'Golden Cross', category: 'Charts', simple: 'A bullish signal when a short-term average crosses above a long-term one', explanation: 'A Golden Cross happens when the 50-day moving average crosses above the 200-day moving average. It\'s considered one of the strongest bullish signals in technical analysis.', tip: 'Institutional investors watch the Golden Cross closely — it can trigger big buying.' },
  { term: 'Death Cross', category: 'Charts', simple: 'A bearish signal when a short-term average falls below a long-term one', explanation: 'The opposite of the Golden Cross. When the 50-day moving average crosses below the 200-day moving average, it signals a potential long-term downtrend.', tip: 'The Death Cross is a warning sign — not always catastrophic, but worth paying attention to.' },
  { term: 'Gap Up / Gap Down', category: 'Charts', simple: 'When a stock opens much higher or lower than it closed', explanation: 'A gap happens when a stock\'s opening price is significantly different from the prior day\'s close — leaving a visible gap on the chart. Gaps are usually caused by earnings reports, major news, or analyst upgrades/downgrades.', example: 'Stock closes at $100, then earnings come out after hours. Next morning it opens at $115 — that\'s a gap up.' },
  { term: 'Average True Range', category: 'Charts', simple: 'How much a stock typically moves in a day', explanation: 'ATR measures the average daily price range (high minus low) over a set period. It tells you how volatile a stock is on a typical day — useful for setting stop losses.', tip: 'A stock with ATR of $5 moves about $5/day on average. Size your trades accordingly.' },

  // ─── Company Health ────────────────────────────────────────────────────────
  { term: 'P/E Ratio', category: 'Company Health', simple: 'How expensive a stock is compared to its profits', explanation: 'Price-to-Earnings ratio = stock price ÷ earnings per share. It shows how much investors pay for every $1 of profit. High P/E = expensive. Low P/E = cheap (or struggling).', example: 'Stock at $100, earns $5/share → P/E of 20. Investors pay $20 per $1 of profit.', tip: 'Compare P/E to competitors, not random numbers.' },
  { term: 'EPS', category: 'Company Health', simple: 'How much profit a company makes per share', explanation: 'Earnings Per Share = total profit ÷ number of shares. It\'s the most important number in an earnings report.', example: 'Company makes $1B profit, has 500M shares → EPS of $2.', tip: 'Analysts predict EPS before earnings. Beating estimates = stock usually goes up.' },
  { term: 'Revenue', category: 'Company Health', simple: 'Total money a company brings in', explanation: 'Revenue is the total sales before any expenses are subtracted. Think of it as the top line — it\'s the first number on an income statement.', tip: 'Revenue growing = good sign. Revenue shrinking = warning sign.' },
  { term: 'Profit Margin', category: 'Company Health', simple: 'What percentage of revenue becomes actual profit', explanation: 'If a company makes $100 in revenue but only keeps $20 after costs, its profit margin is 20%. Higher margins = more efficient business.', example: 'Large tech companies often run 20–30%+ net margins — exceptional compared to most industries.' },
  { term: 'Earnings Report', category: 'Company Health', simple: 'A company\'s quarterly report card', explanation: 'Every 3 months, public companies release their financial results — revenue, profit, and guidance for the future. This often moves the stock price a lot.', tip: 'Stock can drop even on good earnings if it misses expectations. It\'s all relative.' },
  { term: 'Guidance', category: 'Company Health', simple: 'A company\'s prediction for their own future performance', explanation: 'When a company reports earnings, they also say what they expect next quarter. Raising guidance = bullish. Lowering guidance = often tanks the stock.', tip: 'Sometimes guidance matters more than the actual earnings results.' },
  { term: 'Balance Sheet', category: 'Company Health', simple: 'A snapshot of everything a company owns and owes', explanation: 'The balance sheet shows assets (what they own), liabilities (what they owe), and equity (what\'s left over). Healthy company = more assets than liabilities.' },
  { term: 'Debt-to-Equity', category: 'Company Health', simple: 'How much a company borrowed vs. what it actually owns', explanation: 'High debt-to-equity means the company borrowed a lot. This is risky when interest rates are high. Low D/E = financially conservative.', tip: 'Under 1.0 is a common rule of thumb for most businesses — but context matters. Banks, utilities, and real estate companies routinely run D/E above 1.0 by design and are considered healthy. Always compare within the same industry.' },
  { term: 'Free Cash Flow', category: 'Company Health', simple: 'Actual cash left after all expenses', explanation: 'Free cash flow is the real money a company generates after paying for everything. Profitable on paper but negative free cash flow = potential red flag.', tip: 'Warren Buffett focuses heavily on free cash flow.' },
  { term: 'Operating Income', category: 'Company Health', simple: 'Profit from the core business before taxes and interest', explanation: 'Operating income shows how profitable the main business is, ignoring one-time events, taxes, and debt costs. It\'s a cleaner view of business performance than net income.', tip: 'Growing operating income = the core business is getting stronger.' },
  { term: 'Return on Equity', category: 'Company Health', simple: 'How efficiently a company uses shareholder money to make profit', explanation: 'ROE = net income ÷ shareholder equity. It shows how many dollars of profit a company generates per dollar of equity. Higher ROE = more efficient at turning capital into profit.', example: 'Company earns $20M on $100M equity → ROE of 20%.', tip: 'ROE above 15% is often cited as strong — but always compare within the same sector. Capital-light industries (software, finance) naturally have higher ROEs. Also watch out for artificially inflated ROE caused by heavy debt or share buybacks reducing the equity base.' },
  { term: 'Gross Margin', category: 'Company Health', simple: 'Revenue left after subtracting the direct cost of making the product', explanation: 'Gross margin = (revenue − cost of goods sold) ÷ revenue. It shows how profitable the product itself is before operating costs.', example: 'Sell a widget for $100, costs $40 to make → 60% gross margin.', tip: 'Software companies often have 70–80% gross margins. Physical goods are much lower.' },
  { term: 'Analyst Consensus', category: 'Company Health', simple: 'The average opinion of professional stock analysts', explanation: 'Wall Street analysts publish "Buy", "Hold", or "Sell" ratings and price targets on stocks. The consensus is the average view across all analysts covering that stock.', tip: 'Consensus upgrades (from Hold to Buy) often push stocks up. Downgrades can tank them.' },

  // ─── Risk ──────────────────────────────────────────────────────────────────
  { term: 'Volatility', category: 'Risk', simple: 'How wildly a stock\'s price swings', explanation: 'High volatility means the stock price jumps up and down a lot. Low volatility means it moves slowly and steadily. More volatile = more risk AND more potential reward.', example: 'Bitcoin is very volatile. A Treasury bond is very low volatility.' },
  { term: 'Diversification', category: 'Risk', simple: 'Not putting all your eggs in one basket', explanation: 'Spreading your money across different stocks, sectors, and asset types so one bad investment doesn\'t destroy your whole portfolio.', tip: 'Owning 20 different tech stocks isn\'t diversification — they all move together.' },
  { term: 'Short Selling', category: 'Risk', simple: 'Betting that a stock will go down', explanation: 'Short sellers borrow shares, sell them, and hope to buy them back cheaper later. Huge risk — stocks can theoretically rise forever, creating unlimited losses.', tip: 'Short selling carries unlimited downside risk and is generally not suitable for beginners. This is educational context only — not advice.' },
  { term: 'Stop Loss', category: 'Risk', simple: 'An automatic sell order if a stock drops too much', explanation: 'You set a stop loss at, say, 10% below your buy price. If the stock drops that much, it sells automatically so you don\'t lose more.', tip: 'Stop losses are a core risk tool for active traders. Long-term investors often skip them intentionally — different strategies, different rules. Know which style fits you.' },
  { term: 'Margin', category: 'Risk', simple: 'Borrowing money from your broker to buy more stocks', explanation: 'Trading on margin means you use your broker\'s money to buy more than you could with your own cash. Amplifies gains AND losses. Very risky.', tip: 'Never trade on margin as a beginner. You can lose more than you invest.' },
  { term: 'Short Interest', category: 'Risk', simple: 'How many people are betting a stock will fall', explanation: 'High short interest means lots of investors think the stock will drop. If they\'re wrong and the stock rises, they all rush to buy back = short squeeze.', example: 'GameStop 2021 was a famous short squeeze.' },
  { term: 'Beta', category: 'Risk', simple: 'How much a stock moves compared to the overall market', explanation: 'Beta of 1 = moves with the market. Beta of 2 = moves twice as much as the market. Beta of 0.5 = half as volatile as the market.', tip: 'High beta stocks are riskier but can outperform in bull markets.' },
  { term: 'Drawdown', category: 'Risk', simple: 'How much your investment dropped from its peak', explanation: 'Drawdown measures the percentage decline from the highest point to the lowest point in a given period. A 20% drawdown means the investment fell 20% from its peak before recovering.', example: 'Portfolio hits $10,000, drops to $7,500 → 25% drawdown.', tip: 'Professional investors obsess over max drawdown — big drops are psychologically hard to recover from.' },
  { term: 'Correlation', category: 'Risk', simple: 'How closely two investments move together', explanation: 'Correlation of +1 means two assets move perfectly together. -1 means they move in opposite directions. 0 means no relationship. True diversification means owning assets with low correlation.', tip: 'Gold and stocks often have low correlation — that\'s why investors hold both.' },
  { term: 'Hedge', category: 'Risk', simple: 'An investment that offsets losses in another', explanation: 'Hedging means making an investment that gains when your other investment loses. It\'s insurance. Options, inverse ETFs, and gold are common hedges.', tip: 'Hedging costs money (like insurance). You pay for protection whether you need it or not.' },
  { term: 'Risk/Reward Ratio', category: 'Risk', simple: 'Comparing how much you could lose vs. how much you could gain', explanation: 'Before any trade, calculate: if I\'m wrong, how much do I lose? If I\'m right, how much do I gain? A 1:3 ratio means you risk $1 to potentially make $3.', tip: 'A higher ratio isn\'t automatically better — it depends on your win rate. A 1:2 ratio with a 60% win rate can outperform 1:3 with 35% wins. What matters is the combination of both.' },
  { term: 'Position Sizing', category: 'Risk', simple: 'Deciding how much of your money to put in one stock', explanation: 'Position sizing is the process of deciding what percentage of your portfolio to allocate to a single investment. Most pros never risk more than 2–5% of their portfolio on one trade.', tip: 'Concentrating too much in one name amplifies both gains and losses. Most risk management frameworks recommend limiting individual positions to manage downside — but the right size depends on your strategy and conviction level.' },

  // ─── Strategies ───────────────────────────────────────────────────────────
  { term: 'Buy and Hold', category: 'Strategies', simple: 'Buy stocks and keep them for years', explanation: 'The simplest and statistically most effective strategy for most people. Buy quality companies and hold through ups and downs. Time in the market beats timing the market.', tip: 'Warren Buffett\'s favorite strategy.' },
  { term: 'Dollar-Cost Averaging', category: 'Strategies', simple: 'Invest a fixed amount every month no matter what', explanation: 'Instead of investing all at once, you invest the same amount every week or month. You automatically buy more shares when prices are low and fewer when high.', example: 'Invest $100 every month in SPY regardless of price.', tip: 'Removes emotion from investing. Great for beginners.' },
  { term: 'Value Investing', category: 'Strategies', simple: 'Buying stocks that are cheaper than they\'re worth', explanation: 'Value investors look for companies whose stock price doesn\'t reflect their true value. Buy undervalued, wait for the market to recognize it.', tip: 'Warren Buffett and Charlie Munger are legendary value investors.' },
  { term: 'Growth Investing', category: 'Strategies', simple: 'Buying companies growing fast even if expensive', explanation: 'Growth investors focus on companies with rapidly increasing revenue, even if they\'re not yet profitable. High risk, high reward.', example: 'Nvidia, Tesla in early days — high P/E but explosive growth.' },
  { term: 'Momentum Investing', category: 'Strategies', simple: 'Buying stocks that are already going up', explanation: 'The idea: stocks that are rising tend to keep rising, and falling stocks keep falling. Momentum traders ride the trend.', tip: 'Works until it doesn\'t. Always use stop losses.' },
  { term: 'Insider Trading (Legal)', category: 'Strategies', simple: 'Tracking what company executives are buying', explanation: 'When a CEO or CFO buys their own company\'s stock with their own money, it\'s a strong signal they believe in the company\'s future. This is public info filed with the SEC.', tip: 'Our Smart Money page shows this. Executives selling = sometimes concerning. Executives buying = usually bullish.' },
  { term: 'Swing Trading', category: 'Strategies', simple: 'Holding stocks for days to weeks to capture medium-term moves', explanation: 'Swing traders buy stocks they expect to move in the short term — holding for a few days to a few weeks before selling. They use technical analysis to find entry and exit points.', tip: 'Swing trading takes skill and discipline. Much harder than it looks.' },
  { term: 'Index Investing', category: 'Strategies', simple: 'Buying funds that track the whole market instead of picking stocks', explanation: 'Instead of trying to pick winning stocks, you buy index funds that own every stock in an index. You get the market\'s average return — which beats most active investors over time.', example: 'Buy VOO or SPY to own all 500 S&P 500 companies at once.', tip: 'Studies consistently show index investing beats most professional fund managers long-term.' },
  { term: 'Tax-Loss Harvesting', category: 'Strategies', simple: 'Selling losing investments to reduce your tax bill', explanation: 'When you have losing investments, you can sell them to create a "loss" that offsets your gains on winning investments — reducing how much tax you owe.', tip: 'Be careful of the wash-sale rule: you can\'t immediately rebuy the same stock after selling for a loss.' },
]
