export type Category = 'Basics' | 'Charts' | 'Company Health' | 'Risk' | 'Strategies' | 'Options & Bonds'
export const CATEGORIES: readonly ['All', ...Category[]] = ['All', 'Basics', 'Charts', 'Company Health', 'Risk', 'Strategies', 'Options & Bonds']

export interface Term {
  term: string
  category: Category
  simple: string
  explanation: string
  example?: string
  tip?: string
  sections?: { heading: string; body: string }[]
}

export function termToSlug(term: string): string {
  return term
    .toLowerCase()
    .replace(/[\/\(\)]/g, '')
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
}

export const TERMS: Term[] = [
  // ─── Basics ────────────────────────────────────────────────────────────────
  { term: 'Stock', category: 'Basics', simple: 'A tiny piece of ownership in a company', explanation: 'When you buy a stock, you own a small slice of that company. If the company does well, your slice is worth more.', example: 'Buy 1 share of Apple = own a tiny piece of Apple Inc.', tip: 'Think of it like buying a slice of a pizza — you own that slice.' },
  { term: 'Share', category: 'Basics', simple: 'One unit of a stock', explanation: 'A share is just one single piece of a company\'s stock. Companies split their ownership into millions of shares so regular people can afford to buy in.', example: 'Apple has about 15 billion shares. You might own 5 of them.' },
  { term: 'Ticker Symbol', category: 'Basics', simple: 'The short code used to identify a stock', explanation: 'Every publicly traded company has a unique abbreviation called a ticker symbol. It\'s how the market identifies that company. You type it into any trading app to find the stock.', example: 'Apple = AAPL, Tesla = TSLA, Google = GOOGL, Microsoft = MSFT.', tip: 'Ticker symbols are always a few letters long — usually 1 to 5 characters.' },
  { term: 'Market Cap', category: 'Basics', simple: 'Total value of a company', explanation: 'Multiply the stock price by the number of shares. That\'s how much the entire company is worth according to the market.', example: 'Stock at $100 × 1 billion shares = $100B market cap', tip: 'Common convention: under ~$2B = small-cap, $2B–$10B = mid-cap, over $10B = large-cap. Definitions vary — Russell and S&P use different thresholds that shift with each index rebalance.' },
  { term: 'Portfolio', category: 'Basics', simple: 'All your investments together', explanation: 'Your portfolio is the collection of all the stocks, ETFs, and other investments you own. Think of it as your investment "bag."', example: 'You own AAPL, TSLA, and NVDA — those 3 together are your portfolio.' },
  {
    term: 'Dividend',
    category: 'Basics',
    simple: 'Cash a company pays you just for owning their stock',
    explanation: 'When a company earns more profit than it needs to reinvest in the business, it can share that money directly with shareholders as dividends. Most dividends are paid in cash, straight into your brokerage account, usually four times a year (quarterly). You don\'t have to sell your shares or do anything — just own the stock on the right date and the money shows up automatically.',
    example: 'You own 100 shares of Coca-Cola (KO). It pays a quarterly dividend of $0.485 per share. Every three months, $48.50 lands in your brokerage account automatically — that\'s $194 per year just for holding the stock. At a $60 share price, that works out to a 3.2% dividend yield.',
    tip: 'Not all stocks pay dividends. Fast-growing companies like Amazon reinvest every dollar back into the business instead. Dividends tend to come from mature, stable companies — think utilities, consumer brands, and banks — that generate more cash than they can productively reinvest.',
    sections: [
      {
        heading: 'How dividend payments actually work',
        body: 'Every dividend has four key dates. The Declaration Date is when the company announces it. The Ex-Dividend Date is the cutoff — you must own the stock before this date to receive the payment. The Record Date is the official list of shareholders (usually one day after the ex-div date). The Payment Date is when the cash actually hits your account. The ex-dividend date is the one that matters most to investors. Miss it by even one day and you won\'t receive that quarter\'s dividend.',
      },
      {
        heading: 'What is dividend yield?',
        body: 'Dividend yield is the annual dividend payment divided by the current stock price, expressed as a percentage. Formula: Yield = Annual Dividend ÷ Stock Price × 100. Example: a stock that pays $4 per year in dividends and trades at $100 has a 4% yield. A yield of 2–4% is typical for established dividend payers. Yields above 6–7% can look attractive but are often a red flag — they usually mean the stock price has dropped sharply because the company is in trouble, not that the dividend is unusually generous.',
      },
      {
        heading: 'Types of dividends',
        body: 'Cash dividends are the most common — money deposited directly into your brokerage account. Stock dividends pay you in additional shares instead of cash, which grows your position without requiring cash. Special dividends are one-time payments when a company has an unusually large cash surplus to distribute. REITs (real estate investment trusts) and utility companies tend to pay the highest regular dividends because they\'re legally required or structurally set up to distribute most of their earnings.',
      },
      {
        heading: 'Does paying a dividend lower the stock price?',
        body: 'Yes — on the ex-dividend date the stock price drops by roughly the dividend amount. If a stock paying a $1 quarterly dividend was trading at $50, it will typically open near $49 on ex-dividend day. This isn\'t a loss for long-term holders — the cash is now in your account and the price usually recovers quickly. Short-term traders sometimes try to buy before the ex-date and sell after, but this rarely works consistently once taxes and trading costs are factored in.',
      },
      {
        heading: 'Are dividends taxable?',
        body: 'In the US, most dividends from stocks held longer than 60 days are classified as qualified dividends, taxed at the lower long-term capital gains rate (0%, 15%, or 20% depending on your income). Dividends from REITs and some foreign stocks are often taxed as ordinary income at your regular tax rate. Dividends held inside a Roth IRA or 401(k) are not taxed at all — which is a good reason to hold high-dividend stocks in tax-advantaged accounts rather than a regular brokerage.',
      },
    ],
  },
  { term: 'ETF', category: 'Basics', simple: 'A basket of many stocks in one', explanation: 'Instead of buying 500 individual stocks, you buy one ETF that contains all 500. It spreads your risk automatically.', example: 'SPY ETF = owns all 500 companies in the S&P 500.', tip: 'Great for beginners — instant diversification.' },
  { term: 'Index', category: 'Basics', simple: 'A scoreboard for a group of stocks', explanation: 'An index tracks the performance of a specific group of companies. The S&P 500 tracks America\'s 500 biggest companies.', example: 'S&P 500, Dow Jones, and Nasdaq are the three biggest indexes.' },
  { term: 'Bull Market', category: 'Basics', simple: 'When stocks are going up', explanation: 'A bull market is when stock prices are rising and investors are optimistic. Generally means prices are up 20%+ from recent lows.', tip: 'Bulls charge upward — so does the market in a bull market.' },
  { term: 'Bear Market', category: 'Basics', simple: 'When stocks are falling', explanation: 'A bear market means prices have dropped 20% or more from recent highs. Usually tied to recessions or bad economic news.', tip: 'Bears swipe downward — just like a bear market.' },
  { term: 'IPO', category: 'Basics', simple: 'When a company goes public for the first time', explanation: 'An Initial Public Offering is when a private company sells shares to regular people for the first time. It\'s the company\'s debut on the stock market.', example: 'Reddit went public in 2024 — that was their IPO.' },
  { term: 'Broker', category: 'Basics', simple: 'The app or platform where you buy stocks', explanation: 'A broker is the middleman between you and the stock market. Apps like Robinhood, Fidelity, and Schwab are all brokers.', tip: 'Always use a regulated, reputable broker — never random websites.' },
  { term: 'Liquidity', category: 'Basics', simple: 'How easy it is to buy or sell something quickly', explanation: 'A liquid stock has lots of buyers and sellers so you can exit fast. An illiquid stock might take days to sell.', example: 'Apple is very liquid. A tiny penny stock might not be.' },
  { term: 'Sector', category: 'Basics', simple: 'A group of companies in the same type of business', explanation: 'The stock market is divided into sectors — Technology, Healthcare, Finance, Energy, and more. Companies in the same sector tend to move together when news hits their industry.', example: 'Apple, Microsoft, and Nvidia are all in the Technology sector.', tip: 'Diversifying across sectors reduces your risk — don\'t put everything in one industry.' },
  { term: 'Stock Split', category: 'Basics', simple: 'When a company divides its shares into more, cheaper pieces', explanation: 'If a stock is at $1000 and the company does a 10-for-1 split, you get 10 shares worth $100 each. You still own the same total value — it\'s like breaking a $100 bill into ten $10 bills.', example: 'Apple did a 4-for-1 stock split in 2020 to make shares more affordable.', tip: 'Splits don\'t change the company\'s value — just the number of shares.' },
  { term: 'Buyback', category: 'Basics', simple: 'When a company buys back its own shares', explanation: 'Instead of paying dividends, companies sometimes use their profits to repurchase their own shares from the market. This reduces the number of shares, which means each remaining share represents a bigger piece of the company.', tip: 'Buybacks usually push the stock price up. A sign the company thinks its own stock is cheap.' },
  { term: 'Yield', category: 'Basics', simple: 'The income you earn on an investment as a percentage', explanation: 'Yield tells you how much return you\'re getting from a stock\'s dividends or a bond\'s interest, expressed as a percentage of the price you paid.', example: 'Stock costs $100, pays $4/year in dividends = 4% yield.', tip: 'High yields can look attractive but sometimes signal trouble — the price fell sharply.' },
  { term: 'Pre-Market Trading', category: 'Basics', simple: 'Trading that happens before the market officially opens', explanation: 'The stock market officially opens at 9:30 AM ET, but you can trade from 4 AM ET in pre-market. Volume is low and prices can be volatile. Earnings reports often drop before market open, causing big pre-market moves.', tip: 'Pre-market prices can swing wildly. Don\'t panic based on pre-market alone.' },
  { term: 'After-Hours Trading', category: 'Basics', simple: 'Trading after the market closes at 4 PM ET', explanation: 'After the market closes at 4 PM ET, you can still trade until 8 PM ET. Like pre-market, volume is low and spreads are wider. Earnings released after close cause the biggest after-hours moves.', tip: 'The after-hours price often stabilizes once regular trading opens the next day.' },
  { term: 'Blue Chip Stock', category: 'Basics', simple: 'A large, stable, well-known company with a long track record', explanation: 'Blue chip stocks are shares of big, reputable companies — think Apple, Johnson & Johnson, or Coca-Cola. They\'re not the fastest growers but they\'re reliable and often pay dividends.', tip: 'The term comes from poker — blue chips are the highest-value chips.' },
  { term: 'Penny Stock', category: 'Basics', simple: 'A very cheap stock, usually from a tiny or risky company', explanation: 'Penny stocks trade for under $5 per share (often much less). They\'re extremely speculative, easy to manipulate, and most fail. They look cheap but can go to zero fast.', tip: 'Avoid penny stocks as a beginner. "It\'s only $0.10 a share" is not a reason to buy.' },
  { term: 'Mutual Fund', category: 'Basics', simple: 'A pool of money from many investors managed by a professional', explanation: 'A mutual fund collects money from thousands of investors and a fund manager picks stocks or bonds to invest in. Unlike ETFs, mutual funds are priced once per day at market close, not throughout the day.', tip: 'Check the expense ratio. High fees eat into your returns over time.' },
  { term: 'REIT', category: 'Basics', simple: 'A company that owns real estate you can buy like a stock', explanation: 'Real Estate Investment Trusts let regular investors own a piece of commercial real estate — malls, apartments, office buildings — without buying property. REITs must pay out at least 90% of taxable income as dividends.', example: 'Buying shares of a REIT is like owning a tiny piece of a shopping mall.', tip: 'Great for income investors — typically high dividends.' },
  { term: 'Roth IRA', category: 'Basics', simple: 'A retirement account you fund with after-tax money and withdraw from tax-free', explanation: 'A Roth IRA (Individual Retirement Account) is funded with money you\'ve already paid taxes on. It grows tax-free, and when you withdraw it in retirement — including every dollar of gains — you owe zero tax. The 2026 contribution limit is $7,000/year ($8,000 if you\'re 50+), and you need earned income to contribute.', example: 'Start putting in $50/month at 18 instead of waiting until 28. That ten-year head start can leave you with over $100,000 more by retirement, purely from a decade of extra tax-free compounding.', tip: 'Any teenager with earned income — even from babysitting or a part-time job — can open a Roth IRA. The earlier you start, the more decades of tax-free growth you lock in.' },
  { term: '401(k)', category: 'Basics', simple: 'A retirement account through your job, often with free matching money', explanation: 'A 401(k) is an employer-sponsored retirement account. Contributions typically come out of your paycheck before taxes, lowering your taxable income now, and the money grows tax-deferred until retirement (when withdrawals are taxed as regular income). Many employers "match" a percentage of what you contribute — essentially free money.', example: 'Your employer matches 100% of contributions up to 4% of salary. Earning $40,000 and contributing 4% ($1,600) gets you another $1,600 from your employer — an instant 100% return before the money is even invested.', tip: 'Always contribute at least enough to get the full employer match — skipping it means turning down free money. The 2026 contribution limit is $23,500/year (higher with catch-up contributions if you\'re 50+).' },
  { term: 'Inflation', category: 'Basics', simple: 'Prices rising over time, making your money worth less', explanation: 'When inflation is high, $100 buys less stuff than it did last year. The stock market is one of the best ways to protect against inflation since companies can raise their prices too.', tip: 'The Fed targets 2% annual inflation. Above that, they raise interest rates to slow things down.' },
  { term: 'Federal Reserve', category: 'Basics', simple: 'The US central bank that controls interest rates and the money supply', explanation: 'The Fed is basically the bank of banks. It sets the federal funds rate, which influences everything from mortgage rates to credit cards to how stock investors behave. When the Fed raises rates, stocks often fall. When it cuts, stocks often rise.', tip: 'Markets obsess over every Fed statement. "Don\'t fight the Fed" is a famous Wall Street saying.' },
  { term: 'Market Order', category: 'Basics', simple: 'Buy or sell immediately at whatever price is available', explanation: 'A market order executes instantly at the best available price. You\'re guaranteed to get filled, but not at a specific price. Good for liquid, large-cap stocks. Risky for thin, low-volume stocks.', tip: 'For big liquid stocks like AAPL, market orders are fine. For tiny stocks, use a limit order.' },
  { term: 'Limit Order', category: 'Basics', simple: 'Buy or sell only at a specific price or better', explanation: 'A limit order lets you set the exact price you\'re willing to buy or sell at. You might not get filled immediately (or at all), but you won\'t get a worse price than you set.', example: 'Stock is at $102. Set a limit buy at $100 — only buys if price drops to $100 or below.', tip: 'Use limit orders when the price matters. Use market orders when speed matters.' },
  { term: 'Bid-Ask Spread', category: 'Basics', simple: 'The gap between what buyers offer and what sellers want', explanation: 'The bid is the highest price buyers will pay. The ask is the lowest price sellers will accept. The difference between them is the spread — this is a cost of trading. Tight spreads = more liquid market.', example: 'Bid $99.98, Ask $100.00 = $0.02 spread. That\'s your cost to enter and exit.', tip: 'High spreads on small stocks can silently eat your profits.' },
  { term: 'Day Trading', category: 'Basics', simple: 'Buying and selling stocks within the same day', explanation: 'Day traders open and close positions within a single trading day, never holding overnight. It requires extreme focus, speed, and discipline. Studies show the vast majority of day traders lose money.', tip: 'The PDT rule requires $25,000 minimum to make more than 3 day trades per week in the US.' },
  { term: 'Going Long', category: 'Basics', simple: 'Buying a stock expecting it to go up', explanation: 'When you "go long" on a stock, you simply buy it hoping the price rises. This is the most common way people invest — buy low, sell higher.', tip: 'The opposite of shorting. Most regular investors are always "long" the market.' },

  // ─── Charts ────────────────────────────────────────────────────────────────
  { term: 'Candlestick', category: 'Charts', simple: 'A chart shape that shows a stock\'s price movement in a time period', explanation: 'Each candlestick shows the opening price, closing price, highest price, and lowest price for a specific time period. Green = price went up. Red = price went down.', tip: 'The "wick" (thin line) shows the highest and lowest price. The "body" shows open and close.' },
  { term: 'Support Level', category: 'Charts', simple: 'A price where a stock tends to stop falling', explanation: 'Support is a price level where buyers historically step in and stop the stock from dropping further. Like a floor.', example: 'If AAPL keeps bouncing at $150, that\'s a support level.', tip: 'If a stock breaks below support, it often falls a lot further.' },
  { term: 'Resistance Level', category: 'Charts', simple: 'A price where a stock tends to stop rising', explanation: 'Resistance is a price level where sellers historically push the stock back down. Like a ceiling.', example: 'If TSLA keeps failing to break $300, that\'s resistance.', tip: 'If a stock breaks above resistance, it often shoots up fast.' },
  { term: 'Moving Average', category: 'Charts', simple: 'The average price of a stock over a set number of days', explanation: 'A 50-day moving average is the average closing price over the last 50 days. It smooths out daily noise and shows the trend.', tip: 'Stock above its 200-day moving average = generally healthy trend.' },
  { term: 'Volume', category: 'Charts', simple: 'How many shares were traded today', explanation: 'Volume tells you how active a stock is. High volume means lots of buyers and sellers. A big price move on high volume = more credible.', tip: 'Always check volume when a stock spikes. Low volume spike = suspicious.' },
  { term: 'Breakout', category: 'Charts', simple: 'When a stock bursts above a resistance level', explanation: 'A breakout happens when a stock pushes through a price it\'s been stuck below. Often leads to a big move upward.', example: 'Stock stuck at $50 for months suddenly surges to $55 on high volume = breakout.' },
  { term: '52-Week High', category: 'Charts', simple: 'The highest price a stock has been in the last year', explanation: 'The 52-week high shows the peak price over the past 52 weeks. Stocks near their 52-week high are often in strong uptrends.', tip: 'Breaking above a 52-week high is often a very bullish signal.' },
  { term: 'RSI', category: 'Charts', simple: 'A score (0–100) showing if a stock is overbought or oversold', explanation: 'RSI (Relative Strength Index) measures how fast a stock is moving. Above 70 = might be overbought (due for a pullback). Below 30 = might be oversold (due for a bounce).', tip: 'RSI is just one tool — never use it alone.' },
  { term: 'MACD', category: 'Charts', simple: 'A momentum indicator showing when a trend might be changing', explanation: 'MACD (Moving Average Convergence Divergence) compares two moving averages to show whether momentum is building or fading. When the MACD line crosses above the signal line, it\'s a bullish sign. When it crosses below, bearish.', tip: 'Best used with other indicators — not reliable on its own.' },
  { term: 'Bollinger Bands', category: 'Charts', simple: 'Lines around a stock\'s price showing its normal range', explanation: 'Bollinger Bands are three lines: a moving average in the middle, and two bands above and below based on volatility. When a stock touches the upper band, it may be overbought. Lower band = potentially oversold.', tip: 'When the bands squeeze tight, a big move is often coming soon.' },
  { term: 'Golden Cross', category: 'Charts', simple: 'A bullish signal when a short-term average crosses above a long-term one', explanation: 'A Golden Cross happens when the 50-day moving average crosses above the 200-day moving average. It\'s considered one of the strongest bullish signals in technical analysis.', tip: 'Institutional investors watch the Golden Cross closely — it can trigger big buying.' },
  { term: 'Death Cross', category: 'Charts', simple: 'A bearish signal when a short-term average falls below a long-term one', explanation: 'The opposite of the Golden Cross. When the 50-day moving average crosses below the 200-day moving average, it signals a potential long-term downtrend.', tip: 'The Death Cross is a warning sign — not always catastrophic, but worth paying attention to.' },
  { term: 'Gap Up / Gap Down', category: 'Charts', simple: 'When a stock opens much higher or lower than it closed', explanation: 'A gap happens when a stock\'s opening price is significantly different from the prior day\'s close — leaving a visible gap on the chart. Gaps are usually caused by earnings reports, major news, or analyst upgrades/downgrades.', example: 'Stock closes at $100, then earnings come out after hours. Next morning it opens at $115 — that\'s a gap up.' },
  { term: 'Average True Range', category: 'Charts', simple: 'How much a stock typically moves in a day', explanation: 'ATR measures the average daily price range (high minus low) over a set period. It tells you how volatile a stock is on a typical day — useful for setting stop losses.', tip: 'A stock with ATR of $5 moves about $5/day on average. Size your trades accordingly.' },
  { term: 'Head and Shoulders', category: 'Charts', simple: 'A chart pattern that often signals a trend reversal', explanation: 'A head and shoulders pattern has three peaks — a smaller one (left shoulder), a higher one (head), and another smaller one (right shoulder). When the stock breaks below the neckline connecting the troughs, it\'s considered a bearish reversal signal.', tip: 'One of the most well-known reversal patterns. Traders watch the "neckline" closely.' },
  { term: 'Double Bottom', category: 'Charts', simple: 'A "W" shaped pattern that signals a potential reversal upward', explanation: 'A double bottom forms when a stock hits a low, bounces, drops to the same low again, then bounces again. It forms a "W" shape. Breaking above the middle of the W is the bullish signal.', tip: 'The double top is the opposite — an "M" shape that signals a potential drop.' },
  { term: 'Fibonacci Retracement', category: 'Charts', simple: 'Key price levels where a stock might pause or reverse', explanation: 'Based on the Fibonacci sequence, traders use levels like 23.6%, 38.2%, 50%, and 61.8% to predict where a stock might find support or resistance after a big move.', tip: 'The 61.8% level (the "golden ratio") is watched most closely by technical traders.' },
  { term: 'Cup and Handle', category: 'Charts', simple: 'A bullish chart pattern shaped like a coffee cup', explanation: 'The cup forms when a stock gradually drops then rounds back up to its previous high, creating a curved "U" shape. The handle is a short pullback before breaking out. A breakout above the handle is the buy signal.', tip: 'William O\'Neil popularized this pattern. It often precedes significant upward moves.' },

  // ─── Company Health ────────────────────────────────────────────────────────
  { term: 'P/E Ratio', category: 'Company Health', simple: 'How expensive a stock is compared to its profits', explanation: 'Price-to-Earnings ratio = stock price ÷ earnings per share. It shows how much investors pay for every $1 of profit. High P/E = expensive. Low P/E = cheap (or struggling).', example: 'Stock at $100, earns $5/share → P/E of 20. Investors pay $20 per $1 of profit.', tip: 'Compare P/E to competitors, not random numbers.' },
  { term: 'EPS', category: 'Company Health', simple: 'How much profit a company makes per share', explanation: 'Earnings Per Share = total profit ÷ number of shares. It\'s the most important number in an earnings report.', example: 'Company makes $1B profit, has 500M shares → EPS of $2.', tip: 'Analysts predict EPS before earnings. Beating estimates = stock usually goes up.' },
  { term: 'Revenue', category: 'Company Health', simple: 'Total money a company brings in', explanation: 'Revenue is the total sales before any expenses are subtracted. Think of it as the top line — it\'s the first number on an income statement.', tip: 'Revenue growing = good sign. Revenue shrinking = warning sign.' },
  { term: 'Profit Margin', category: 'Company Health', simple: 'What percentage of revenue becomes actual profit', explanation: 'If a company makes $100 in revenue but only keeps $20 after costs, its profit margin is 20%. Higher margins = more efficient business.', example: 'Large tech companies often run 20–30%+ net margins — exceptional compared to most industries.' },
  { term: 'Earnings Report', category: 'Company Health', simple: 'A company\'s quarterly report card', explanation: 'Every 3 months, public companies release their financial results — revenue, profit, and guidance for the future. This often moves the stock price a lot.', tip: 'Stock can drop even on good earnings if it misses expectations. It\'s all relative.' },
  { term: 'Guidance', category: 'Company Health', simple: 'A company\'s prediction for their own future performance', explanation: 'When a company reports earnings, they also say what they expect next quarter. Raising guidance = bullish. Lowering guidance = often tanks the stock.', tip: 'Sometimes guidance matters more than the actual earnings results.' },
  { term: 'Balance Sheet', category: 'Company Health', simple: 'A snapshot of everything a company owns and owes', explanation: 'The balance sheet shows assets (what they own), liabilities (what they owe), and equity (what\'s left over). Healthy company = more assets than liabilities.' },
  { term: 'Debt-to-Equity', category: 'Company Health', simple: 'How much a company borrowed vs. what it actually owns', explanation: 'High debt-to-equity means the company borrowed a lot. This is risky when interest rates are high. Low D/E = financially conservative.', tip: 'Under 1.0 is a common rule of thumb for most businesses — but context matters. Banks, utilities, and real estate companies routinely run D/E above 1.0 by design and are considered healthy. Always compare within the same industry.' },
  { term: 'Free Cash Flow', category: 'Company Health', simple: 'Actual cash left after all expenses', explanation: 'Free cash flow is the real money a company generates after paying for everything. Profitable on paper but negative free cash flow = potential red flag.', tip: 'Warren Buffett focuses heavily on free cash flow.' },
  { term: 'Operating Income', category: 'Company Health', simple: 'Profit from the core business before taxes and interest', explanation: 'Operating income shows how profitable the main business is, ignoring one-time events, taxes, and debt costs. It\'s a cleaner view of business performance than net income.', tip: 'Growing operating income = the core business is getting stronger.' },
  { term: 'Return on Equity', category: 'Company Health', simple: 'How efficiently a company uses shareholder money to make profit', explanation: 'ROE = net income ÷ shareholder equity. It shows how many dollars of profit a company generates per dollar of equity. Higher ROE = more efficient at turning capital into profit.', example: 'Company earns $20M on $100M equity → ROE of 20%.', tip: 'ROE above 15% is often cited as strong — but always compare within the same sector. Capital-light industries (software, finance) naturally have higher ROEs. Also watch out for artificially inflated ROE caused by heavy debt or share buybacks reducing the equity base.' },
  { term: 'Gross Margin', category: 'Company Health', simple: 'Revenue left after subtracting the direct cost of making the product', explanation: 'Gross margin = (revenue − cost of goods sold) ÷ revenue. It shows how profitable the product itself is before operating costs.', example: 'Sell a widget for $100, costs $40 to make → 60% gross margin.', tip: 'Software companies often have 70–80% gross margins. Physical goods are much lower.' },
  { term: 'Analyst Consensus', category: 'Company Health', simple: 'The average opinion of professional stock analysts', explanation: 'Wall Street analysts publish "Buy", "Hold", or "Sell" ratings and price targets on stocks. The consensus is the average view across all analysts covering that stock.', tip: 'Consensus upgrades (from Hold to Buy) often push stocks up. Downgrades can tank them.' },
  { term: 'EBITDA', category: 'Company Health', simple: 'Earnings before interest, taxes, depreciation, and amortization', explanation: 'EBITDA strips out accounting costs and financing decisions to show the raw profitability of a business. It\'s widely used to compare companies across different tax and capital structures.', example: 'Two companies earn different net incomes, but similar EBITDA — the difference is how they\'re financed, not how the business actually runs.', tip: 'Warren Buffett is skeptical of EBITDA — depreciation is a real cost, he argues. Know the limits.' },
  { term: 'Price-to-Sales (P/S)', category: 'Company Health', simple: 'How much investors pay for each dollar of a company\'s revenue', explanation: 'P/S ratio = market cap ÷ annual revenue. Useful for valuing companies that aren\'t profitable yet. A P/S of 5 means investors pay $5 for every $1 of revenue.', tip: 'Growth stocks often have high P/S. The question is whether growth justifies the premium.' },
  { term: 'Price-to-Book (P/B)', category: 'Company Health', simple: 'Stock price vs. the company\'s net assets', explanation: 'P/B ratio compares a company\'s market value to its book value (assets minus liabilities). A P/B under 1 means you\'re buying assets for less than their accounting value — potentially a bargain or a value trap.', tip: 'Most useful for banks and asset-heavy industries. Less meaningful for software companies.' },
  { term: 'Forward P/E', category: 'Company Health', simple: 'P/E ratio based on expected future earnings, not past ones', explanation: 'Instead of using last year\'s earnings, forward P/E uses analysts\' earnings estimates for the next 12 months. It\'s more forward-looking and usually lower than trailing P/E for growing companies.', tip: 'Forward P/E assumes analysts\' estimates are right — they often aren\'t. Treat it as a directional guide.' },
  { term: 'Working Capital', category: 'Company Health', simple: 'A company\'s short-term financial cushion', explanation: 'Working capital = current assets − current liabilities. It shows whether a company can cover its short-term bills. Positive = fine. Negative = potential cash crunch ahead.', tip: 'Companies can be profitable on paper but still run out of cash. Working capital reveals this.' },
  { term: 'Book Value', category: 'Company Health', simple: 'What a company is worth on paper if you sold everything and paid all debts', explanation: 'Book value = total assets − total liabilities. It\'s the accounting value of a company, not what the market thinks it\'s worth. Market value often far exceeds book value for strong brands and tech companies.', tip: 'If a stock trades below book value, the market may think the assets are worth less than stated — or it\'s a hidden gem.' },

  // ─── Risk ──────────────────────────────────────────────────────────────────
  { term: 'Volatility', category: 'Risk', simple: 'How wildly a stock\'s price swings', explanation: 'High volatility means the stock price jumps up and down a lot. Low volatility means it moves slowly and steadily. More volatile = more risk AND more potential reward.', example: 'Bitcoin is very volatile. A Treasury bond is very low volatility.' },
  { term: 'Diversification', category: 'Risk', simple: 'Not putting all your eggs in one basket', explanation: 'Spreading your money across different stocks, sectors, and asset types so one bad investment doesn\'t destroy your whole portfolio.', tip: 'Owning 20 different tech stocks isn\'t diversification — they all move together.' },
  { term: 'Short Selling', category: 'Risk', simple: 'Betting that a stock will go down', explanation: 'Short sellers borrow shares, sell them, and hope to buy them back cheaper later. Huge risk — stocks can theoretically rise forever, creating unlimited losses.', tip: 'Short selling carries unlimited downside risk and is generally not suitable for beginners. This is educational context only — not advice.' },
  { term: 'Stop Loss', category: 'Risk', simple: 'An automatic sell order if a stock drops too much', explanation: 'You set a stop loss at, say, 10% below your buy price. If the stock drops that much, it sells automatically so you don\'t lose more.', tip: 'Stop losses are a core risk tool for active traders. Long-term investors often skip them intentionally — different strategies, different rules. Know which style fits you.' },
  { term: 'Margin', category: 'Risk', simple: 'Borrowing money from your broker to buy more stocks', explanation: 'Trading on margin means you use your broker\'s money to buy more than you could with your own cash. Amplifies gains AND losses. Very risky.', tip: 'Never trade on margin as a beginner. You can lose more than you invest.' },
  { term: 'Short Interest', category: 'Risk', simple: 'How many people are betting a stock will fall', explanation: 'High short interest means lots of investors think the stock will drop. If they\'re wrong and the stock rises, they all rush to buy back = short squeeze.', example: 'GameStop 2021 was a famous short squeeze.' },
  { term: 'Beta', category: 'Risk', simple: 'How much a stock moves compared to the overall market', explanation: 'Beta of 1 = moves with the market. Beta of 2 = moves twice as much as the market. Beta of 0.5 = half as volatile as the market.', tip: 'High beta stocks are riskier but can outperform in bull markets.' },
  { term: 'Drawdown', category: 'Risk', simple: 'How much your investment dropped from its peak', explanation: 'Drawdown measures the percentage decline from the highest point to the lowest point in a given period. A 20% drawdown means the investment fell 20% from its peak before recovering.', example: 'Portfolio hits $10,000, drops to $7,500 → 25% drawdown.', tip: 'Professional investors obsess over max drawdown — big drops are psychologically hard to recover from.' },
  { term: 'Correlation', category: 'Risk', simple: 'How closely two investments move together', explanation: 'Correlation of +1 means two assets move perfectly together. -1 means they move in opposite directions. 0 means no relationship. True diversification means owning assets with low correlation.', tip: 'Gold and stocks often have low correlation — that\'s why investors hold both.' },
  { term: 'Hedge', category: 'Risk', simple: 'An investment that offsets losses in another', explanation: 'Hedging means making an investment that gains when your other investment loses. It\'s insurance. Options, inverse ETFs, and gold are common hedges.', tip: 'Hedging costs money (like insurance). You pay for protection whether you need it or not.' },
  { term: 'Risk/Reward Ratio', category: 'Risk', simple: 'Comparing how much you could lose vs. how much you could gain', explanation: 'Before any trade, calculate: if I\'m wrong, how much do I lose? If I\'m right, how much do I gain? A 1:3 ratio means you risk $1 to potentially make $3.', tip: 'A higher ratio isn\'t automatically better — it depends on your win rate. A 1:2 ratio with a 60% win rate can outperform 1:3 with 35% wins. What matters is the combination of both.' },
  { term: 'Position Sizing', category: 'Risk', simple: 'Deciding how much of your money to put in one stock', explanation: 'Position sizing is the process of deciding what percentage of your portfolio to allocate to a single investment. Most pros never risk more than 2–5% of their portfolio on one trade.', tip: 'Concentrating too much in one name amplifies both gains and losses. Most risk management frameworks recommend limiting individual positions to manage downside — but the right size depends on your strategy and conviction level.' },
  { term: 'Black Swan', category: 'Risk', simple: 'A rare, unpredictable event that causes massive market disruption', explanation: 'A black swan is an extreme, unexpected event nobody saw coming — like the 2008 financial crisis or COVID-19 crash. The name comes from the old assumption that black swans didn\'t exist.', tip: 'You can\'t predict black swans, but you can prepare: hold cash, diversify, don\'t use leverage.' },
  { term: 'Counterparty Risk', category: 'Risk', simple: 'The risk that the other side of a deal can\'t hold up their end', explanation: 'Counterparty risk is the chance that whoever you\'re doing a financial deal with defaults or fails. It\'s why people worried about banks during 2008 — if your bank fails, your money is at risk.', tip: 'FDIC insurance covers up to $250,000 per account. Above that, counterparty risk is real.' },
  { term: 'Concentration Risk', category: 'Risk', simple: 'Too much money in one stock, sector, or asset type', explanation: 'Concentration risk is when too much of your portfolio is tied to one thing. If 60% of your money is in one stock and it crashes, you\'re in serious trouble. Diversification is the antidote.', example: 'Employees who had most of their 401(k) in Enron stock lost everything when it collapsed.', tip: 'Even if you love a company, cap it. No single stock should dominate your portfolio.' },
  { term: 'Leverage', category: 'Risk', simple: 'Using borrowed money or financial instruments to amplify your investment', explanation: 'Leverage magnifies both gains and losses. 2x leverage means if the market goes up 10%, you gain 20%. But if it drops 10%, you lose 20%. Enough leverage can wipe out your entire account.', tip: 'Leverage is a double-edged sword. Professionals use it carefully. Beginners should avoid it.' },

  // ─── Strategies ───────────────────────────────────────────────────────────
  { term: 'Buy and Hold', category: 'Strategies', simple: 'Buy stocks and keep them for years', explanation: 'The simplest and statistically most effective strategy for most people. Buy quality companies and hold through ups and downs. Time in the market beats timing the market.', tip: 'Warren Buffett\'s favorite strategy.' },
  { term: 'Dollar-Cost Averaging', category: 'Strategies', simple: 'Invest a fixed amount every month no matter what', explanation: 'Instead of investing all at once, you invest the same amount every week or month. You automatically buy more shares when prices are low and fewer when high.', example: 'Invest $100 every month in SPY regardless of price.', tip: 'Removes emotion from investing. Great for beginners.' },
  { term: 'Value Investing', category: 'Strategies', simple: 'Buying stocks that are cheaper than they\'re worth', explanation: 'Value investors look for companies whose stock price doesn\'t reflect their true value. Buy undervalued, wait for the market to recognize it.', tip: 'Warren Buffett and Charlie Munger are legendary value investors.' },
  { term: 'Growth Investing', category: 'Strategies', simple: 'Buying companies growing fast even if expensive', explanation: 'Growth investors focus on companies with rapidly increasing revenue, even if they\'re not yet profitable. High risk, high reward.', example: 'Nvidia, Tesla in early days — high P/E but explosive growth.' },
  { term: 'Momentum Investing', category: 'Strategies', simple: 'Buying stocks that are already going up', explanation: 'The idea: stocks that are rising tend to keep rising, and falling stocks keep falling. Momentum traders ride the trend.', tip: 'Works until it doesn\'t. Always use stop losses.' },
  { term: 'Insider Trading (Legal)', category: 'Strategies', simple: 'Tracking what company executives are buying', explanation: 'When a CEO or CFO buys their own company\'s stock with their own money, it\'s a strong signal they believe in the company\'s future. This is public info filed with the SEC.', tip: 'Our Smart Money page shows this. Executives selling = sometimes concerning. Executives buying = usually bullish.' },
  { term: 'Swing Trading', category: 'Strategies', simple: 'Holding stocks for days to weeks to capture medium-term moves', explanation: 'Swing traders buy stocks they expect to move in the short term — holding for a few days to a few weeks before selling. They use technical analysis to find entry and exit points.', tip: 'Swing trading takes skill and discipline. Much harder than it looks.' },
  { term: 'Index Investing', category: 'Strategies', simple: 'Buying funds that track the whole market instead of picking stocks', explanation: 'Instead of trying to pick winning stocks, you buy index funds that own every stock in an index. You get the market\'s average return — which beats most active investors over time.', example: 'Buy VOO or SPY to own all 500 S&P 500 companies at once.', tip: 'Studies consistently show index investing beats most professional fund managers long-term.' },
  { term: 'Tax-Loss Harvesting', category: 'Strategies', simple: 'Selling losing investments to reduce your tax bill', explanation: 'When you have losing investments, you can sell them to create a "loss" that offsets your gains on winning investments — reducing how much tax you owe.', tip: 'Be careful of the wash-sale rule: you can\'t immediately rebuy the same stock after selling for a loss.' },
  { term: 'Sector Rotation', category: 'Strategies', simple: 'Moving money between sectors depending on the economic cycle', explanation: 'Different sectors outperform at different points in the economic cycle. Investors rotate into defensive sectors (healthcare, utilities) during downturns and into cyclical sectors (tech, consumer discretionary) during expansions.', tip: 'Timing sector rotation perfectly is very hard. Most retail investors are better off staying diversified.' },
  { term: 'Rebalancing', category: 'Strategies', simple: 'Adjusting your portfolio back to your target allocation', explanation: 'Over time, winning investments grow to dominate your portfolio. Rebalancing means selling some winners and buying more of the underperformers to get back to your original target mix. It forces you to sell high and buy low automatically.', example: 'Target: 70% stocks, 30% bonds. Stocks rally → now 85/15. Rebalance by selling stocks and buying bonds.', tip: 'Rebalance once or twice a year, not every week.' },
  { term: 'Dividend Growth Investing', category: 'Strategies', simple: 'Investing in companies that consistently grow their dividend every year', explanation: 'Instead of chasing yield, dividend growth investors look for companies that raise their payout year after year. A stock yielding 2% that grows its dividend 10% annually is more valuable long-term than a 6% yield that never grows.', example: 'Dividend Aristocrats are S&P 500 companies that have raised dividends 25+ consecutive years.', tip: 'Dividend growth = management confidence in the future. Companies rarely raise dividends before bad times.' },
  { term: 'Contrarian Investing', category: 'Strategies', simple: 'Buying what everyone else is selling, and selling what everyone is buying', explanation: 'Contrarians believe the crowd is usually wrong at extremes. When everyone is panicking and selling, a contrarian buys. When everyone is euphoric and buying, a contrarian gets cautious.', tip: '"Be fearful when others are greedy, and greedy when others are fearful." — Warren Buffett' },
  { term: 'DRIP', category: 'Strategies', simple: 'Automatically reinvesting dividends to buy more shares', explanation: 'A Dividend Reinvestment Plan automatically uses your dividend payments to buy more shares instead of sending you cash. Over decades, this compounding effect dramatically boosts returns.', example: '$10,000 in a dividend stock at 3% yield — DRIP vs. spending dividends makes a massive difference after 30 years.', tip: 'Most brokers offer automatic DRIP at no cost. Turn it on and forget it.' },

  // ─── Options & Bonds ──────────────────────────────────────────────────────
  { term: 'Call Option', category: 'Options & Bonds', simple: 'A contract giving you the right to buy a stock at a set price', explanation: 'A call option gives you the right (not obligation) to buy 100 shares of a stock at the "strike price" before the expiration date. If the stock rises above the strike price, your call gains value.', example: 'Buy a $150 call on Apple. AAPL rises to $175. Your call is worth at least $25 per share.', tip: 'Options can expire worthless. Never put money in options you can\'t afford to lose completely.' },
  { term: 'Put Option', category: 'Options & Bonds', simple: 'A contract giving you the right to sell a stock at a set price', explanation: 'A put option gives you the right to sell 100 shares at the strike price before expiration. If the stock falls below the strike, your put gains value. Puts are often used as insurance (hedges) against a stock you own.', example: 'Own Apple stock at $175. Buy a $160 put. If AAPL crashes to $120, your put is worth at least $40 per share.', tip: 'Buying puts as portfolio insurance is called "protective puts" — a legitimate risk management strategy.' },
  { term: 'Strike Price', category: 'Options & Bonds', simple: 'The price at which an option lets you buy or sell', explanation: 'The strike price is the fixed price written into an options contract. For a call, you want the stock to go above the strike. For a put, you want it to go below.', tip: 'Options with strike prices close to the current stock price are "at the money." Far away = "out of the money."' },
  { term: 'Expiration Date', category: 'Options & Bonds', simple: 'The last day an option can be used', explanation: 'Every options contract has an expiration date. If the option is not profitable (in the money) by expiration, it expires worthless and you lose 100% of what you paid for it.', tip: 'Time decay accelerates as expiration approaches. Options lose value every day they don\'t move your way.' },
  { term: 'Implied Volatility', category: 'Options & Bonds', simple: 'The market\'s expectation of how much a stock will move', explanation: 'Implied volatility (IV) is baked into option prices. High IV = expensive options (the market expects big moves). Low IV = cheap options. IV spikes before earnings reports.', tip: 'Buying options when IV is sky-high can mean you need a massive move just to break even.' },
  { term: 'Bond', category: 'Options & Bonds', simple: 'A loan you give to a company or government that pays you interest', explanation: 'When you buy a bond, you\'re lending money to a company or government. They pay you regular interest (the "coupon") and return your principal when the bond matures. Bonds are generally safer than stocks but lower return.', example: 'Buy a 10-year Treasury bond at 4.5% yield — the government pays 4.5% annually and returns your money in 10 years.', tip: 'When interest rates rise, bond prices fall. When rates fall, bond prices rise. They move opposite.' },
  { term: 'Yield Curve', category: 'Options & Bonds', simple: 'A graph showing interest rates at different loan lengths', explanation: 'The yield curve shows interest rates on bonds ranging from short-term (3 months) to long-term (30 years). Normally, longer bonds pay more. When it "inverts" (short-term higher than long-term), it\'s historically predicted recessions.', tip: 'An inverted yield curve has preceded every US recession in recent decades — one of the most watched economic signals.' },
  { term: 'Credit Rating', category: 'Options & Bonds', simple: 'A grade for how likely a borrower is to repay their debt', explanation: 'Agencies like Moody\'s, S&P, and Fitch rate bonds from AAA (safest) to D (in default). Higher-rated bonds pay lower interest. Junk bonds (below BBB) pay higher interest because they\'re riskier.', tip: 'If a company\'s credit rating gets downgraded to junk, its stock usually tanks and borrowing costs spike.' },
  { term: 'Covered Call', category: 'Options & Bonds', simple: 'Selling someone else the right to buy your stock at a higher price', explanation: 'If you own a stock, you can sell a call option against it to collect premium income. If the stock stays below the strike, you keep the premium. If it rises above, you sell your shares at the strike price.', example: 'Own Apple at $170. Sell a $185 call for $3. Keep $300/contract if AAPL stays under $185.', tip: 'A great way to generate income on stocks you plan to hold. But caps your upside if the stock rockets.' },
]
